
global MEMA_SCREEN_DIMENSIONS
MEMA_SCREEN_DIMENSIONS: str = "1280x800"

global MEMA_BUTTON_COLOURS
MEMA_BUTTON_COLOURS: list[str] = ["#F5FFC6", "#B4E1FF", "#AB87FF", "#C1FF9B"]

global MEMA_CONTENT_WIDTH, MEMA_BUTTON_WIDTH
MEMA_CONTENT_WIDTH = 8
MEMA_BUTTON_WIDTH = 3